name: Audit deps

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  audit-docs:
    defaults:
      run:
        working-directory: ./docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm audit

  audit-playground:
    defaults:
      run:
        working-directory: ./examples/playground
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm audit

  audit-package:
    defaults:
      run:
        working-directory: ./package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm audit

  audit-key-extractor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2
        with:
          working-directory: key-extractor
          token: ${{ secrets.GITHUB_TOKEN }}
